// noesis-engine / prop-sprites
// Pixel-art sprite definitions for static props. Each entry has:
//   rows: string[] of pixel chars, colors: { char: hex }, mainKey: char.

export const PROP_SPRITES = {
  sun: {
    rows: [
      '.........r.........',
      '........rrr........',
      '....r...rrr...r....',
      '...rr..ooooo..rr...',
      '..rrrooOOOOOoorrr..',
      '....ooOOOOOOOoo....',
      '....oOOWWWWWOOo....',
      '...oOOWWWYWWWOOo...',
      '.rroOOWWYYYWWOOorr.',
      'rrroOOWYYYYYWOOorrr',
      '.rroOOWWYYYWWOOorr.',
      '...oOOWWWYWWWOOo...',
      '....oOOWWWWWOOo....',
      '....ooOOOOOOOoo....',
      '..rrrooOOOOOoorrr..',
      '...rr..ooooo..rr...',
      '....r...rrr...r....',
      '........rrr........',
      '.........r.........',
    ],
    palette: { Y: '#fff6cc', W: '#ffe89a', O: '#f6c84a', o: '#e8a52a', r: '#e8902a' },
    mainKey: 'O',
  },
  moon: {
    rows: [
      '......ww......',
      '...wwwwwMMM...',
      '..wwwwwMMMMM..',
      '.wwwwwMMMMMMM.',
      '.wwwcMMMMMMMM.',
      '.wwwMkMMMMMMm.',
      'wwwMMMMMcMMmmm',
      'wwMcMMMMMkmmmm',
      '.MMMkMMMMmmmm.',
      '.MMMMcMMmmcmd.',
      '.MMMMMkmmmmkd.',
      '..MMMMmcmmdd..',
      '...MMmmmkdd...',
      '......mm......',
    ],
    palette: { w: '#fbfdff', M: '#e8ecf4', m: '#aeb8cf', d: '#8d97b3', c: '#bcc6da', k: '#9aa4be' },
    mainKey: 'M',
  },
  star: {
    rows: [
      '.....W.....',
      '.....W.....',
      '....WYW....',
      '.S..WYW..S.',
      '..SSWYWSS..',
      'WWYYYOYYYWW',
      '..SSWYWSS..',
      '.S..WYW..S.',
      '....WYW....',
      '.....W.....',
      '.....W.....',
    ],
    palette: { W: '#f6d24a', Y: '#fff3b8', O: '#fff6d8', S: '#e0a82a' },
    mainKey: 'W',
  },
  cactus: {
    rows: [
      '.....ff.....',
      '....CcCC....',
      '...wCcCCw...',
      '....CcCC....',
      '.cC.CcCC.Cc.',
      '.cC.CcCC.Cc.',
      '.cCwCcCCwCc.',
      '.cC.CcCC.Cc.',
      '.cCCCcCCCCc.',
      '..ccCcCCcc..',
      '....CcCC....',
      '...wCcCCw...',
      '....CcCC....',
      '....CcCC....',
      '....CcCC....',
      '...wCcCCw...',
      '....CcCC....',
      '....CcCC....',
      '...dCcCCd...',
      '...dddddd...',
    ],
    palette: { C: '#4f8a5e', c: '#3a6b47', w: '#e8e2d2', f: '#ff85a8', d: '#2e5232' },
    mainKey: 'C',
  },
  palm: {
    rows: [
      '.........gggg.........',
      '...gggg..gggg..GGGG...',
      '..ggggggggggggGGGGGG..',
      '.ggg..gggggggGGGG..GG.',
      'ggg....ggooGGGG.....GG',
      'gg......oooGGG.......G',
      'g..........Tt........G',
      '...........Tt.........',
      '...........ww.........',
      '...........Tt.........',
      '............Tt........',
      '............Tt........',
      '............ww........',
      '............Tt........',
      '.............Tt.......',
      '.............Tt.......',
      '.............ww.......',
      '.............Tt.......',
      '.............Tt.......',
      '.............Tt.......',
      '.............Tt.......',
      '.............Tt.......',
      '...........ttTtt......',
      '..........tttttt......',
      '........wwwwwwwwww....',
      '..........wwwwww......',
    ],
    palette: { g: '#62b272', G: '#3c734a', o: '#7a4a28', T: '#a5763f', t: '#7d5630', w: '#5a4022' },
    mainKey: 'g',
  },
  crate: {
    rows: [
      'NKKKKKKKN',
      'KpwppppwK',
      'KppopptpK',
      'KpwppppwK',
      'BBBBBBBBB',
      'KpwppppwK',
      'KptppopwK',
      'KpwppppwK',
      'NKKKKKKKN',
    ],
    palette: { N: '#5a3f24', K: '#7a5630', p: '#b5894f', w: '#caa066', t: '#9a6f3f', o: '#8a5e30', B: '#6e4a28' },
    mainKey: 'p',
  },
  barrel: {
    rows: [
      '..hBhhhhhhbb..',
      '..hBbbBbbBbb..',
      '.hbBbbBbbBbbB.',
      '.HHGGGGGGGGGG.',
      '.hbBbbBbbBbbB.',
      '.hbBbbBbbBbbB.',
      'BbbBbbBbbBbbBb',
      'BbbBbbBbbBbbBb',
      'HHGGGGGGGGGGGG',
      'BbbBbbBbbBbbBb',
      '.hbBbbBbbBbbB.',
      '.hbBbbBbbBbbB.',
      '.hbBbbBbbBbbB.',
      '.HHGGGGGGGGGG.',
      '..hBbbBbbBbb..',
      '..hBbddddBbb..',
    ],
    palette: { h: '#a5763f', b: '#7a5530', B: '#5f421f', G: '#4a5563', H: '#8a93a0', d: '#2a1e10' },
    mainKey: 'b',
  },
  streetlamp: {
    rows: [
      '.....BBBB.....',
      '.....bssb.....',
      '....ssLLss....',
      '...bsLYYLsb...',
      '...bsLYYLsb...',
      '...bsLYYLsb...',
      '....ssLLss....',
      '.....bssb.....',
      '....BBBBBB....',
      '......pb......',
      '.....bpbb.....',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '.....bbbb.....',
      '....bbbbbb....',
      '...BBBBBBBB...',
      '..BBBBBBBBBB..',
    ],
    palette: { B: '#1c242c', b: '#2a343c', s: '#F4AC1D', L: '#fff3c4', Y: '#fff0bf', p: '#3a4654' },
    mainKey: 's',
  },
  gem: {
    rows: [
      '....lwwwl....',
      '...ltttttl...',
      '..ltwtttttl..',
      '.ltttttttttl.',
      'GGGGGlllddddd',
      '.GGGGllldddd.',
      '.GGGGllldddd.',
      '..GGGwllddd..',
      '..GGGlllddd..',
      '...GGllldd...',
      '....Glwld....',
      '....Gllld....',
      '.....lll.....',
      '......l......',
      '......l......',
    ],
    palette: { w: '#fbfdff', t: '#bfe6ff', l: '#7cc4f0', G: '#5bb0e8', d: '#3a7fc4' },
    mainKey: 'G',
  },
  coin: {
    rows: [
      '..CCCC..',
      '.CwwwwC.',
      'CwWWWWwC',
      'CwWssWwC',
      'CwWssWwC',
      'CwWWWWwC',
      '.CwwwwC.',
      '..cccc..',
    ],
    palette: { C: '#e0a82a', c: '#b8821a', w: '#f6d24a', W: '#fff3b8', s: '#c8881a' },
    mainKey: 'W',
  },
  balloon: {
    rows: [
      '...hhh...',
      '..hhhBB..',
      '.hhhBBBB.',
      '.hhBBBBB.',
      'hBBBBBBbb',
      '.BBBBBbb.',
      '.BBBBbbb.',
      '..Bbbbb..',
      '...bbb...',
      '....k....',
      '....s....',
      '.....s...',
      '....s....',
    ],
    palette: { h: '#ffd1e0', B: '#ff6b95', b: '#cc4a72', k: '#b83e63', s: '#aab3c8' },
    mainKey: 'B',
  },
  rocket: {
    rows: [
      '......R......',
      '.....RRR.....',
      '....RRRRR....',
      '...RRRRRRR...',
      '..RWWWWWWWR..',
      '..RWWWWWWWR..',
      '..RWWbbbWWR..',
      '..RWbBlbWWR..',
      '..RWWbbbWWR..',
      '..RWWWWWWWR..',
      '..RWWWWWWWR..',
      '..RrWWWWWrR..',
      '.RRrWWWWWrRR.',
      'RRRrWWWWWrRRR',
      'R.RrWWWWWrR.R',
      '...rWWWWWr...',
      '....nnnnn....',
      '....oOoOo....',
      '.....ofo.....',
    ],
    palette: { R: '#c44a3e', W: '#eef1ea', b: '#3a5fb0', B: '#1f3a6e', l: '#bcd4ff', r: '#9a3a30', n: '#6e7884', o: '#e0683c', O: '#f6a83c', f: '#f6e08a' },
    mainKey: 'R',
  },
  planet: {
    rows: [
      '......hhh......',
      '....hhhhhhh....',
      '..hhhhhhhhhbb..',
      '..pppppppppbb..',
      '.ppppppppppbbb.',
      '.ppppPppppPbbb.',
      'PPPPPPPPPPPpppp',
      'PPPPPPPPPPPpppp',
      'pPPPPpPPPPppppp',
      '.pppSSpppppbbb.',
      '.pppSppppppbbb.',
      '..pppPppppPbb..',
      '..PPPPPPPPPpp..',
      '....PPPPPPP....',
      '......PPP......',
    ],
    palette: { P: '#5b8def', p: '#4a76c4', h: '#8fb4e8', b: '#3a5da0', S: '#e8a96a' },
    mainKey: 'P',
    secondaryKey: 'S',
    shades: { h: ['#ffffff', 0.30], p: ['#000000', 0.18], b: ['#000000', 0.40] },
  },
  building: {
    rows: [
      '........o.........................',
      '........a.........................',
      '........a.........................',
      '...RRRRRRRRRRRRRRRRRRRRRRRRRRRR...',
      '.LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRbb.',
      '.LRRRRRRRRRRRRRRRRRRRRRRRRRRRRRbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBYYYYBBBuuuuBBBYYYYBBBYYYYBbb.',
      '.LBBBWWWWBBBuuuuBBBWWWWBBBWWWWBbb.',
      '.LBBBWWWWBBBuuuuBBBWWWWBBBWWWWBbb.',
      '.LBBBssssBBBssssBBBssssBBBssssBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBYYYYBBBYYYYBBBYYYYBBBuuuuBbb.',
      '.LBBBWWWWBBBWWWWBBBWWWWBBBuuuuBbb.',
      '.LBBBWWWWBBBWWWWBBBWWWWBBBuuuuBbb.',
      '.LBBBssssBBBssssBBBssssBBBssssBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBuuuuBBBYYYYBBBuuuuBBBYYYYBbb.',
      '.LBBBuuuuBBBWWWWBBBuuuuBBBWWWWBbb.',
      '.LBBBuuuuBBBWWWWBBBuuuuBBBWWWWBbb.',
      '.LBBBssssBBBssssBBBssssBBBssssBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBYYYYBBBYYYYBBBYYYYBBBYYYYBbb.',
      '.LBBBWWWWBBBWWWWBBBWWWWBBBWWWWBbb.',
      '.LBBBWWWWBBBWWWWBBBWWWWBBBWWWWBbb.',
      '.LBBBssssBBBssssBBBssssBBBssssBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBYYYYBBBYYYYBBBuuuuBBBYYYYBbb.',
      '.LBBBWWWWBBBWWWWBBBuuuuBBBWWWWBbb.',
      '.LBBBWWWWBBBWWWWBBBuuuuBBBWWWWBbb.',
      '.LBBBssssBBBssssBBBssssBBBssssBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbb.',
      '.LBBBYYYYBBBBBddddddBBBBBBuuuuBbb.',
      '.LBBBWWWWBBBBBDDDDoDBBBBBBuuuuBbb.',
      '.LBBBWWWWBBBBBDDDDoDBBBBBBuuuuBbb.',
      '.LBBBBBBBBBBBBDDDDoDBBBBBBBBBBBbb.',
      '.LBBBBBBBBBBBBDDDDoDBBBBBBBBBBBbb.',
      '.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.',
      'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
    ],
    palette: { R: '#1a2138', L: '#3a4468', B: '#2c3454', b: '#222a46', Y: '#ffe9b0', W: '#F4AC1D', u: '#141a30', s: '#454f78', D: '#5a4022', d: '#3a2a18', o: '#F4AC1D', a: '#8a93ab', n: '#11162c' },
    mainKey: 'B', secondaryKey: 'W',
  },
  coral: {
    rows: [
      '.H....H...H.',
      '.C....C...C.',
      '.C.H..C..HC.',
      '.CcC..Cc..C.',
      '..CC..C...C.',
      '..Cc.HC..cC.',
      '..C..CC..C..',
      '..Cc.C..cC..',
      '...C.Cc.C...',
      '...CcC..C...',
      '....CC.cC...',
      '....CCcC....',
      '...cCCCCc...',
      '..ddddddddd.',
    ],
    palette: { H: '#ffa08a', C: '#e8705e', c: '#c4503e', d: '#9c352b' },
    mainKey: 'C',
  },
  seaweed: {
    rows: [
      '..H......',
      '..s...H..',
      '.ss...s..',
      '.s...ss..',
      '.sS..s...',
      '..s..sS..',
      '..sS..s..',
      '...s..s..',
      '..sS.ss..',
      '..s..s...',
      '.sS..sS..',
      '.s....s..',
      '.sS..sS..',
      '..s..s...',
      '..sSss...',
      '..dssd...',
      '.ddddd...',
    ],
    palette: { H: '#6fc093', s: '#3f9a6e', S: '#2c7350', d: '#1f5238' },
    mainKey: 's',
  },
  table: {
    rows: [
      'hhhhhhhhhhhhhhhhhhhh',
      'TTTTlTTTTTTTlTTTTTTT',
      'TTTTTTTTlTTTTTTTTlTT',
      '.ssssssssssssssssss.',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '..Ts............sT..',
      '.WWW..........WWWW..',
    ],
    palette: { h: '#a5763f', T: '#7a5530', l: '#5f421f', s: '#4a3318', W: '#2a1e10' },
    mainKey: 'T',
  },
  chair: {
    rows: [
      '.hh....hh.',
      '.Ts....sT.',
      '.TsllllsT.',
      '.Ts....sT.',
      '.TsllllsT.',
      '.Ts....sT.',
      '.TsllllsT.',
      '.Ts....sT.',
      'hhhhhhhhhh',
      'TTTTlTTTTT',
      '.Ts....sT.',
      '.Ts....sT.',
      '.Ts....sT.',
      '.Ts....sT.',
      '.Ts....sT.',
      '.Ts....sT.',
      '.Ts....sT.',
      '.WW....WW.',
    ],
    palette: { h: '#a5763f', T: '#7a5530', l: '#5f421f', s: '#4a3318', W: '#2a1e10' },
    mainKey: 'T',
  },
  plant: {
    rows: [
      '...G...',
      '..GgG..',
      '.GgGgG.',
      'GgGGGgG',
      '.GgGgG.',
      '..gGg..',
      '...|...',
      '..PpP..',
      '.PpppP.',
      '.PPPPP.',
      '.eeeee.',
    ],
    palette: { G: '#6cb074', g: '#3f7a4b', '|': '#5a4022', P: '#b35040', p: '#7a2f25', e: '#5a2a22' },
    mainKey: 'G',
  },
  blackboard: {
    rows: [
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFff',
      'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFff',
      'FFBBBBBBBBBBBBBBBBBBBBBBBBBGBBff',
      'FFBBBBBBBBBBBBBBGBBBBGBBBBBGBBff',
      'FFBBBBBBBBBBBBBBBBBBBBBBBBBBBBff',
      'FFBBBcBccBccBccBBGBBBBBBBBBBBBff',
      'FFBBBBBBBBBBGBBBGBBBBBGBcccBBBff',
      'FFBBBGBBBBBBBBBBBBBBBBBcBBBcBBff',
      'FFBBBBBBBGBBBBBBBBBBBBBBBBBBBBff',
      'FFBBBBcccBcccBcccBcccBcBBBBBcBff',
      'FFBBBBBBBBBBBBBBBBBBBBBBBBBBBBff',
      'FFBBBBBBBBBBBBBBBBBBBBBcBBBcBBff',
      'FFGBBBBBBBBGBBBBBBGBBBBBcccBBBff',
      'FFBBBBccBccBBGBGBBBBBBBBBBBBBBff',
      'FFBBBBBBBBBBBBBBBBBBBBBBBBBBBBff',
      'FFBBBBBBGBBBBBBBBBBBBBBBGBBBBBff',
      'FFBBBBBBBBBBBBBBBBBBBBBBBBBBBBff',
      'FFBBBGBBBBGBBBBBBBBBBBBBBBBBBGff',
      'FFBBBBBBBBBBBBBBBGBBBBBBBBBBBBff',
      'ffffffffffffffffffffffffffffffff',
      'ffffffffffffffffffffffffffffffff',
      '..FFFFppFFFFFFFFFFFFFFFFFFFFFF..',
      '....ff....................ff....',
      '....ff....................ff....',
    ],
    palette: { F: '#8a653a', f: '#5a4022', B: '#1f3024', G: '#2a3e30', c: 'rgba(248,237,229,0.82)', p: '#e8d9bd' },
    mainKey: 'B',
  },
  lamp: {
    rows: [
      '...hSSSSs...',
      '..hSSSSSSs..',
      '..hSSSSSSs..',
      '.hSSSSSSSSs.',
      '.hSSSSSSSSs.',
      'hSSSSSSSSSSs',
      '...YYYYYY...',
      '.....yy.....',
      '.....pb.....',
      '.....pb.....',
      '....bpbb....',
      '.....pb.....',
      '.....pb.....',
      '.....pb.....',
      '.....pb.....',
      '.....pb.....',
      '.....pb.....',
      '....bbbb....',
      '..bbbbbbbb..',
      '...dddddd...',
    ],
    palette: { h: '#e8c894', S: '#d8b27a', s: '#a8854e', Y: '#fff0bf', y: '#F4AC1D', p: '#3a4654', b: '#2a343c', d: '#1a1f2e' },
    mainKey: 'S',
  },
  tree: {
    rows: [
      '............HHH...........',
      '........HHHHHHHHHHG.......',
      '.......HHHHGHHHHHGGG......',
      '......HHHHGGGHHHGGGGg.....',
      '......HHHGGGGGGGGGGgg.....',
      '....HHHGGGGGGGGGGGggHGG...',
      '...HHHHGGGGgGGGGfggHGGGG..',
      '...HHHHGGGgGGGGGGgGGGGGGG.',
      '..HHHHGfGGGGGGGGgGGGGGGgg.',
      '..HHHGGGGGGGGGgggGGGGGggg.',
      '..HGGGGGGGgGGgggGGGGGgggg.',
      '..GGGGGGgggGGGGGGGGgfgggd.',
      '..GGGGGgggGGGGGGgGgggggdd.',
      '...GGGggggGfGGGggggggdddd.',
      '...GgggggGGGGgggggggdddd..',
      '....ggggGGGGgggggdgdddd...',
      '......ddGGGggggfddddd.....',
      '........Ggggggddddd.......',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '...........TT||...........',
      '.........TTTT||||.........',
      '.......wwwwwwwwwwww.......',
      '.........wwwwwwww.........',
    ],
    palette: { H: '#79b86e', G: '#5b9a66', g: '#3e6e47', d: '#2e5232', f: '#F4AC1D', T: '#7a5a30', '|': '#5a4022', w: '#3a2a18' },
    mainKey: 'G',
  },
  book: {
    rows: [
      '..HHHHHHH.',
      '.cCCCBCCH.',
      '.cCCCBCCPp',
      '.cCCCBCCPp',
      '.cCCCCCCPp',
      '.cCCCCCCPp',
      '.ccccccccp',
      '..pppppp..',
    ],
    palette: { H: '#e87560', C: '#c44a3e', c: '#9c352b', B: '#F4AC1D', P: '#f2e8d8', p: '#d8c9ae' },
    mainKey: 'C',
  },
  sign: {
    rows: [
      '.hhhhhhhhhhhh.',
      '.WmmmWmWmmWWW.',
      '.WWWWWWWWWWWW.',
      '.WmmWmmmWmmWW.',
      '.wwwwwwwwwwww.',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '......pb......',
      '.....bppb.....',
      '....dddddd....',
    ],
    palette: { h: '#a5763f', W: '#8a653a', m: '#4a3318', w: '#5f421f', p: '#7a5530', b: '#4a3318', d: '#2a1e10' },
    mainKey: 'W',
  },
  rock: {
    rows: [
      '...hhRR....',
      '..hRRRRr...',
      '.hRRrRRrr..',
      '.RRmRRRRr..',
      '.RmmRRrrr..',
      'rRRRrrrr.Rr',
      '.sssssss.ss',
    ],
    palette: { h: '#aab3c8', R: '#8a93ab', r: '#646e88', m: '#5a8a52', s: '#3a3f55' },
    mainKey: 'R',
  },
  door: {
    rows: [
      'FFFFFFFFFFFFff',
      'FFFFFFFFFFFFff',
      'FFddddddddddff',
      'FFddddddddddff',
      'FFddhhhhhhddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhDDDDDddff',
      'FFddddddddddff',
      'FFddddddddkkff',
      'FFddhhhhhhddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhddddDddff',
      'FFddhDDDDDddff',
      'ffddddddddddff',
      'ffddddddddddff',
      'ffffffffffffff',
    ],
    palette: { F: '#8a653a', f: '#2a1e10', d: '#5a4022', h: '#a5763f', D: '#3a2a18', k: '#F4AC1D' },
    mainKey: 'd',
  },
  rug: {
    rows: [
      'fPPPPPPPPPPPPPPPPPPf',
      'fPRRRRRRRRRRRRRRRRPf',
      'fPRRpRRRRppRRRRpRRPf',
      'fPRpRpRRpRRpRRpRpRPf',
      'fPRRpRRRRppRRRRpRRPf',
      'fPRRRRRRRRRRRRRRRRPf',
      'fPPPPPPPPPPPPPPPPPPf',
    ],
    palette: { f: '#d8c9ae', P: '#7a3346', R: '#a64a3e', p: '#e0a82a' },
    mainKey: 'R',
  },
  'rug-stripes': {
    rows: [
      'fRRRAAARRRAAARRRAAAf',
      'fRRRaaaRRRaaaRRRaaaf',
      'fRRRAAARRRAAARRRAAAf',
      'frrrAAArrrAAArrrAAAf',
      'fRRRAAARRRAAARRRAAAf',
      'fRRRaaaRRRaaaRRRaaaf',
      'fRRRAAARRRAAARRRAAAf',
      'frrrAAArrrAAArrrAAAf',
    ],
    palette: { f: '#d8c9ae', R: '#a64a3e', r: '#8a3d34', A: '#e0a82a', a: '#b8821a' },
    mainKey: 'R',
  },
  'rug-medallion': {
    rows: [
      'fdddddddddddddddddf',
      'fdRRRRRRRRRRRRRRRdf',
      'fdRARRRRRARRRRRARdf',
      'fdRRRRRAAAAARRRRRdf',
      'fdRRRRAAAaAAARRRRdf',
      'fdRRAAAaadaaAAARRdf',
      'fdRRRRAAAaAAARRRRdf',
      'fdRRRRRAAAAARRRRRdf',
      'fdRARRRRRARRRRRARdf',
      'fdRRRRRRRRRRRRRRRdf',
      'fdddddddddddddddddf',
    ],
    palette: { f: '#d8c9ae', R: '#3f5d8a', d: '#2e4568', A: '#e0a82a', a: '#b8821a' },
    mainKey: 'R',
  },
  'rug-checker': {
    rows: [
      'frrrrrrrrrrrrrrrrrrf',
      'fRRAARRAaRRaARRAARRf',
      'fRRAaRRaARRAARRAaRRf',
      'fAARRAaRRaARRAARRAaf',
      'fAaRRaARRAARRAaRRaAf',
      'fRRAaRRaARRAARRAaRRf',
      'fRRaARRAARRAaRRaARRf',
      'frrrrrrrrrrrrrrrrrrf',
    ],
    palette: { f: '#d8c9ae', R: '#4f8a5e', r: '#3a6b47', A: '#e8d9bd', a: '#c9b896' },
    mainKey: 'R',
  },
  candle: {
    rows: [
      '...W...',
      '..WfW..',
      '..fof..',
      '...k...',
      '..Wcn..',
      '..Wcn..',
      '..Wcnn.',
      '..Wcn..',
      '.WWcnn.',
      '.Bbbbb.',
      'BbbbbbB',
    ],
    palette: { W: '#fffaf0', f: '#F4AC1D', o: '#e8742a', k: '#5a4022', c: '#fbe9b8', n: '#d8c69e', B: '#c89a3a', b: '#8a6420' },
    mainKey: 'c',
  },
  flower: {
    rows: [
      '...HHP...',
      '..HPPPp..',
      '.HPyYyPp.',
      '.PPYYYpp.',
      '.PpyYypp.',
      '..Ppppp..',
      '....s....',
      '....s....',
      '.GGGs....',
      '..ggsGGG.',
      '....s.gg.',
      '...dsd...',
    ],
    palette: { H: '#ffd1e4', P: '#ff4985', p: '#cc2f63', Y: '#ffd45e', y: '#e89a10', s: '#3e6e47', G: '#5b9a66', g: '#4f8a4f', d: '#2e5232' },
    mainKey: 'P',
  },
  bush: {
    rows: [
      '....HHHH.....',
      '..HHLLLLHH...',
      '.HLLLLLLLLH..',
      '.LLgLLbLLLLL.',
      'LLLLLgLLgLLLL',
      'LbLLLLLLLLbLL',
      '.LgLLgLLLgLL.',
      '..dLLLLLLd...',
      '...ddddddd...',
    ],
    palette: { H: '#79b86e', L: '#5b9a66', g: '#3e6e47', d: '#2e5232', b: '#c44a3e' },
    mainKey: 'L',
  },
  bench: {
    rows: [
      '.hhhhhhhhhhhhhhhhhhhh.',
      '.TTTTlTTTTTTlTTTTTTTT.',
      '..Ts...............sT.',
      '..Ts...............sT.',
      'hhhhhhhhhhhhhhhhhhhhhh',
      'TTTTTTlTTTTTTTlTTTTTTT',
      '.ssssssssssssssssssss.',
      '..Ts...............sT.',
      '..Ts...............sT.',
      '..Ts...............sT.',
      '..Ts...............sT.',
      '.WWW..............WWW.',
    ],
    palette: { h: '#a5763f', T: '#7a5530', l: '#5f421f', s: '#4a3318', W: '#2a1e10' },
    mainKey: 'T',
  },
  fountain: {
    rows: [
      '......b.W.........',
      '........Wb.b......',
      '.....b..WW..b.....',
      '........Wb........',
      '........WW........',
      '.....SSSSSSSS.....',
      '......wwwwww......',
      '.....ssssssss.....',
      '.......SSss.......',
      '.......SSss.......',
      '.......SSss.......',
      '.......SSss.......',
      '.......SSss.......',
      '..SSSSSSSSSSSSSS..',
      '.wwwWwwwwbwwwWwww.',
      '.wwwwwbwwwwWwwwww.',
      '.ssssssssssssssss.',
      '..nnnnnnnnnnnnnn..',
      '....nnnnnnnnnn....',
      '.....dddddddd.....',
    ],
    palette: { S: '#a8b0bd', s: '#7c8694', n: '#5a626e', w: '#4aa3e0', W: '#bfe6ff', b: '#7cc4f0', d: '#3a3f55' },
    mainKey: 'w',
  },
  mushroom: {
    rows: [
      '....OOO....',
      '..OORRRRr..',
      '.ORRwRRRRr.',
      '.ORwwRRwRr.',
      'ORRRRRwwRRr',
      'ORRwRRRRRrr',
      '.uuuuuuuuu.',
      '...Wttn....',
      '...Wttn....',
      '..Wttttn...',
      '...ddddd...',
    ],
    palette: { O: '#e87560', R: '#c44a3e', r: '#9c352b', w: '#fbe9b8', u: '#7a2820', W: '#f8f0dd', t: '#e8d9bd', n: '#bfae8e', d: '#3a3f55' },
    mainKey: 'R',
  },
  'path-tile': {
    rows: [
      '.hhhh.h.',
      'hssssghh',
      'hsssrgsr',
      '.srrr.r.',
    ],
    palette: { h: '#b8c0d4', s: '#8a93ab', r: '#646e88', g: '#3a3f55' },
    mainKey: 's',
  },
  'flower-cluster': {
    rows: [
      '.PP..AA...',
      'PwP.AwA.BB',
      '.PP..AA.wB',
      '..s..s..B.',
      '..s.Gs..s.',
      '.GsG.s.Gs.',
      '..s..s..s.',
      '..dd.dd.d.',
    ],
    palette: { P: '#ff4985', w: '#fff3b8', A: '#F4AC1D', B: '#5b8def', s: '#3e6e47', G: '#5b9a66', d: '#2e5232' },
    mainKey: 'P',
  },
  pokeball: {
    rows: [
      '...RRRRR...',
      '..RhhhhrR..',
      '.RhHhRRrrR.',
      'RhHhRRRrrrR',
      'RrhRRRRRrrR',
      'RrRRRRRRrrR',
      'KKKKBxBKKKK',
      'kKBwWoWBKkK',
      'WWWBwxwBWWW',
      '.WWwwwwwWW.',
      '..WwwwwwW..',
    ],
    palette: {
      R: '#c84a3f', h: '#e9786a', H: '#f8b8a8', r: '#8a2e22',
      K: '#1F2547', k: '#0a1230', B: '#3a4a72', x: '#0a1230',
      W: '#FBFAF6', w: '#c8c2b2', o: '#6E7896'
    },
    mainKey: 'R',
  },
  pedestal: {
    rows: [
      '.MMMMMMMMMMMM.',
      'cMMMMMMMMMMMMc',
      '..cmmmmmmmmc..',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '...HmsmsmsS...',
      '..cmmmmmmmmc..',
      'cMMMMMMMMMMMMc',
      '.MMMMMMMMMMMM.',
      '..dddddddddd..',
    ],
    palette: { M: '#b8bfcc', c: '#8d97b3', H: '#d4dae6', m: '#a3abc0', s: '#7c8694', S: '#5a626e', d: '#3a3f55' },
    mainKey: 'M',
  },
  computer: {
    rows: [
      '.MMMMMMMMMM.',
      'MMrrrrrrrrAM',
      'MMTssssssssM',
      'MMTssGGGsssM',
      'MMTsGgGgGssM',
      'MMTssGGGsssM',
      'MMTssssssssM',
      'MMtttttttttM',
      '.MMMMMMMMMM.',
      '..kKKKKKKk..',
      '.LLLLLLLLLL.',
    ],
    palette: {
      M: '#2a3540', r: '#1a2530', A: '#F4AC1D',
      T: '#0a1408', t: '#0a1408',
      s: '#1a3825', G: '#9ce0a8', g: '#6cb074',
      k: '#3a4250', K: '#6E7896', L: '#5a4022'
    },
    mainKey: 'M',
  },
  bookshelf: {
    rows: [
      'FfFFFFFFFFFFFFFFFFFFFFfF',
      'FffffffffffffffffffffffF',
      'FfDeeDDDDDDDDDDrrDDDDDfF',
      'FfeeeDDDDrrDDDDrrurruufF',
      'FfeeeDeDurreeDurrurruufF',
      'FfeeeDeDurreeDurrurruufF',
      'FfeeeDeDurreeDurrurruufF',
      'FfeeeDeDurreeDurrurruufF',
      'FfFFFFFFFFFFFFFFFFFFFFfF',
      'FfDDDDDDDDDDuDDDDDDDaafF',
      'FfDeeuuuuDeeuDeeuuDDaafF',
      'FfDeeuuuuDeeuDeeuupDaafF',
      'FfDeeuuuuDeeuDeeuupDaafF',
      'FfDeeuuuuDeeuDeeuupDaafF',
      'FfDeeuuuuDeeuDeeuupDaafF',
      'FfFFFFFFFFFFFFFFFFFFFFfF',
      'FfDDDDDDDDDDeeDDppDDDDfF',
      'FfeeruuDDDDpeerrppeeeefF',
      'FfeeruuaaaDpeerrppeeeefF',
      'FfeeruuaaaDpeerrppeeeefF',
      'FfeeruuaaaDpeerrppeeeefF',
      'FfeeruuaaaDpeerrppeeeefF',
      'FfFFFFFFFFFFFFFFFFFFFFfF',
      'FffffffffffffffffffffffF',
    ],
    palette: { F: '#8a653a', f: '#5a4022', D: '#241a10', r: '#c44a3e', u: '#5b8def', e: '#4f8a5e', a: '#F4AC1D', p: '#e8d9bd' },
    mainKey: 'F',
  },
  lighthouse: {
    rows: [
      '........kk........',
      '......kkkkkk......',
      '.....kYYYYYYk.....',
      '.....kYYYYYYk.....',
      '.....kYYYYYYk.....',
      '.....kYYYYYYk.....',
      '....kkkkkkkkkk....',
      '....RRRRRRRRRrr...',
      '....RRRRRRRRRrr...',
      '....RRRRRRRRRrr...',
      '....RRRRRRRRRrr...',
      '....WWWWWWWWWnn...',
      '...WWWWWWWWWWWnn..',
      '...WWWWWWWWWWWnn..',
      '...WWWWWWWWWWWnn..',
      '...RRRRRRRRRRRrr..',
      '...RRRRRRRRRRRrr..',
      '...RRRRRRRRRRRrr..',
      '...RRRRRRRRRRRrr..',
      '...WWWWWWWWWWWnn..',
      '..WWWWWWWWWWWWWnn.',
      '..WWWWWWWWWWWWWnn.',
      '..WWWWWWWWWWWWWnn.',
      '..RRRRRRRRRRRRRrr.',
      '..RRRRRRRRRRRRRrr.',
      '..RRRRRRRRRRRRRrr.',
      '..RRRRRRRRRRRRRrr.',
      '..WWWWWWWWWWWWWnn.',
      '.WWWWWWWDDWWWWWWnn',
      '.WWWWWWWDDWWWWWWnn',
      '.WWWWWWWDDWWWWWWnn',
      '.RRRRRRRDDRRRRRRrr',
      '.RRRRRRRDDRRRRRRrr',
      '..kkkkkkkkkkkkkk..',
      '.kkkkkkkkkkkkkkkk.',
      '...nnnnnnnnnnnn...',
    ],
    palette: { k: '#2a3138', Y: '#ffe9b0', R: '#c44a3e', r: '#9c352b', W: '#f0ece2', n: '#c9c2b2', D: '#3a2a18' },
    mainKey: 'R',
  },
  boat: {
    rows: [
      '........Maa.....',
      '........M.......',
      '........MSS.....',
      '........MSS.....',
      '......SSMSSS....',
      '......SSMSSSS...',
      '.....SSSMSSSS...',
      '.....SSSMSSSSS..',
      '....SSSSMssssss.',
      '....ssssMssssss.',
      '...sssssMssssss.',
      '...wwwwwMwwwwww.',
      '........M.......',
      '.hWWWWWWWWWWWWW.',
      '.HHHHHHHHHHHHHH.',
      '..HHHHHHHHHHxx..',
      '....xxxxxxxx....',
      '.....dddddd.....',
    ],
    palette: { a: '#F4AC1D', M: '#5f421f', S: '#f0ece2', s: '#c9c2b2', w: '#7a5530', W: '#a5763f', h: '#c49a6a', H: '#8a4a2e', x: '#5e3220', d: '#3a3f55' },
    mainKey: 'H',
  },
  lightbulb: {
    rows: [
      '............',
      '.y..oooo..y.',
      '...ooYYoo...',
      '..ooYYYYoo..',
      '..oYYWWYYo..',
      'y.oYWWWWYo.y',
      '..oYYWWYYo..',
      '..ookYYkoo..',
      '...ookkoo...',
      '....oooo....',
      '....oooo....',
      '...MMMMMM...',
      '...mmmmmm...',
      '...MMMMMM...',
      '.....mm.....',
    ],
    palette: { y: '#f4ac1d', W: '#fff6d8', Y: '#ffe89a', o: '#f4ac1d', k: '#8a6420', M: '#aab3c8', m: '#7c8694' },
    mainKey: 'Y',
  },
  hourglass: {
    rows: [
      'hTTTTTTTTTTT',
      'Tg.........g',
      'T.gSSSSSSSgt',
      'T..gSSSSSg.t',
      'T...gSSSg..t',
      'T....S.g...t',
      'T....s.g...t',
      'T....S.....t',
      'T....s.g...t',
      'T...gS..g..t',
      'T..g.s...g.t',
      'T.g..S....gt',
      'TgSSSSSSSSSg',
      'TgSSSSSSSSSg',
      'TTTTTTTTTTTT',
      '..dddddddd..',
    ],
    palette: { h: '#a5763f', T: '#7a5530', t: '#5f421f', g: '#bfd8e8', S: '#e8c068', s: '#c89a3a', d: '#2a1e10' },
    mainKey: 'S',
  },
  scale: {
    rows: [
      '.......MM.......',
      'mMMMMMMMMMMMMMMm',
      '.c.....Mm.....c.',
      '.c.....Mm.....c.',
      '.c.....Mm.....c.',
      '.c.....Mm.....c.',
      'MMMMM..Mm..MMMMM',
      '.mmm...Mm...mmm.',
      '.......Mm.......',
      '.......Mm.......',
      '.......Mm.......',
      '.......Mm.......',
      '......MMMm......',
      '.....MMMMMm.....',
      '....MMMMMMMm....',
      '.....dddddd.....',
    ],
    palette: { M: '#e0a82a', m: '#b8821a', c: '#8a6420', d: '#3a3f55' },
    mainKey: 'M',
  },
  magnifier: {
    rows: [
      '............',
      '...MMMM.....',
      '..WwtttM....',
      '.MtWttttM...',
      '.MttttttM...',
      '.MttttttM...',
      '.MttttttM...',
      '..MttttM....',
      '...MMMM.Ts..',
      '.........Ts.',
      '..........Ts',
      '...........T',
      '............',
      '............',
    ],
    palette: { M: '#7c8694', t: '#bfe6ff', W: '#fbfdff', w: '#dff0ff', T: '#7a5530', s: '#4a3318' },
    mainKey: 'M',
  },
  key: {
    rows: [
      '..MhM.........',
      '.M...M........',
      '.M...MMMMMMMM.',
      '.M...Mmmmmmmm.',
      '..MMM....m..m.',
      '.........m..m.',
    ],
    palette: { h: '#f6d24a', M: '#e0a82a', m: '#b8821a' },
    mainKey: 'M',
  },
  trophy: {
    rows: [
      '.MMMMMMMMMMMM.',
      'cMWWMMMMMMMMmc',
      'cMWWMMMMMMMMmc',
      'c.MMMMMMMMMm.c',
      '.c.MMMMMMMm.c.',
      '..cMMMMMMMmc..',
      '...MMMMMMm....',
      '....MMMMm.....',
      '......Mm......',
      '......Mm......',
      '.....MMMm.....',
      '....TTTTTT....',
      '...TTPPPPTT...',
      '...TTTTTTTT...',
      '..dddddddddd..',
      '..............',
    ],
    palette: { M: '#e0a82a', m: '#b8821a', W: '#fff3b8', c: '#8a6420', T: '#7a5530', P: '#f4ac1d', d: '#3a3f55' },
    mainKey: 'M',
  },
  flag: {
    rows: [
      '.TAAAAAAAA',
      '.TAAAAAAa.',
      '.TAAAAa...',
      '.TAAa.....',
      '.Ta.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      '.Tt.......',
      'TTTt......',
      '.ddd......',
    ],
    palette: { T: '#7a5530', t: '#5f421f', A: '#f4ac1d', a: '#c8881a', d: '#2a1e10' },
    mainKey: 'A',
  },
  flask: {
    rows: [
      '....g..g....',
      '....g..g....',
      '....g..g....',
      '....g..g....',
      '...g....g...',
      '...g....g...',
      '..g......g..',
      '..gLLLLLLg..',
      '.gLLlLLLLLg.',
      '.gLLLLLLLLg.',
      'gLLLLLlLLLLg',
      'gLlLLLLLLLLg',
      'gLLLLLLLLLLg',
      'gggggggggggg',
      '.dddddddddd.',
    ],
    palette: { g: '#bfd8e8', L: '#5b8def', l: '#9fc4ff', d: '#3a3f55' },
    mainKey: 'L',
  },
  globe: {
    rows: [
      '..............',
      '....hhhhBB....',
      '...hhhhBBBB...',
      '..hhGGGBBBBB..',
      '..hhhGGGBBGB..',
      '.hhhBBBBGBBBB.',
      '.hhBBBBBBGBBb.',
      '.hBGBBBBGBBbb.',
      '..BGGBBBBGbb..',
      '..BBGGBBBbbb..',
      '...BBBBBbbb...',
      '....BBBbbb....',
      '..............',
      '......m...m...',
      '......m..m....',
      '......m.m.....',
      '....MMMMMM....',
      '.....dddd.....',
    ],
    palette: { h: '#6fa3e0', B: '#3f7dc4', b: '#2e5da0', G: '#4f8a5e', m: '#8a6420', M: '#7a5530', d: '#3a3f55' },
    mainKey: 'B',
  },
  scroll: {
    rows: [
      'hc..........ch',
      'PcPPPPPPPPPPcP',
      'PcPmmPmmmPPPcP',
      'PcPPPPPPPPPPcP',
      'PcPmmmPmmPPPcP',
      'PcPPPPPPPPPPcP',
      'PcPmmPmmmmPPcP',
      'PcPPPPPPPPPPcP',
      'pcppppppppppcp',
      '.dd........dd.',
    ],
    palette: { h: '#e8dcc0', c: '#c9b896', P: '#f2e8d8', p: '#d8c9ae', m: '#8a7350', d: '#3a3f55' },
    mainKey: 'P',
  },
  gear: {
    rows: [
      '..............',
      '....MM..MM....',
      '....MMMMMM....',
      '....WMMMMM....',
      '.MMWMMMMMMMMM.',
      '.MMMMkkkkMMMM.',
      '..MMMk..kMmm..',
      '..MMMk..kmmm..',
      '.mmMMkkkkmmmm.',
      '.mmMMmmmmmmmm.',
      '....mmmmmm....',
      '....mmmmmm....',
      '....mm..mm....',
      '..............',
    ],
    palette: { M: '#aab3c8', m: '#7c8694', k: '#4a5563', W: '#d4dae6' },
    mainKey: 'M',
  },
  mountain: {
    rows: [
      '.........S................',
      '........SSs...............',
      '........SSs...............',
      '.......SSSss..............',
      '.......RRRrrr......S......',
      '......RRRRrrr.....SSs.....',
      '......RRRRrrrr....SSs.....',
      '.....RRRRRrrrr...SSSss....',
      '.....RRRRRrrrrr..RRRrr....',
      '....RRRRRRrrrrrrRRRRrrr...',
      '...RRRRRRRrrrrrrRRRRrrr...',
      '...RRRRRRRrrrrrrrRRRrrrr..',
      '..RRRRRRRRrrrrrrrrRRrrrr..',
      '..RRRRRRRRrrrrrrrrRRrrrrr.',
      '.RRRRRRRRRrrrrrrrrrRrrrrr.',
      '.RRRRRRRRRrrrrrrrrrRrrrrrr',
      'RRRRRRRRRRrrrrrrrrrrrrrrrr',
      'dddddddddddddddddddddddddd',
    ],
    palette: { S: '#eef2f8', s: '#c5cfdd', R: '#8a93ab', r: '#5a6378', d: '#3a3f55' },
    mainKey: 'R',
  },
  pomegranate: {
    rows: [
      '.....cc.....',
      '....cccc....',
      '...RRRRRR...',
      '..RRRRRRRR..',
      '.RRRssssRRR.',
      '.RRsssWsssR.',
      '.RRssssssRR.',
      '.RRRssssRRR.',
      '..RRRRRRRR..',
      '..dRRRRRRd..',
      '...dddddd...',
      '....dddd....',
    ],
    palette: { c: '#7a3a2a', R: '#b0393a', d: '#6e2020', s: '#e0445f', W: '#ff9fae' },
    mainKey: 'R',
  },
  column: {
    rows: [
      'KKKKKKKK',
      'KMMMMMMK',
      '.MMMMMM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MsMMsM.',
      '.MMMMMM.',
      'KMMMMMMK',
      'KKKKKKKK',
      'dddddddd',
    ],
    palette: { K: '#2a3040', M: '#3c4356', s: '#272c3a', d: '#171b26' },
    mainKey: 'M',
  },
};

// Tamaño natural por tipo: el scale que recibe un prop cuando la escena no
// declara uno. Curado para que las proporciones salgan coherentes contra el
// personaje de referencia (un aprendiz hero a scale 5 mide ~55 px): la flor
// a la rodilla, la mesa a la cintura, el árbol al doble de la persona, el
// edificio dominando. Una escena siempre puede overridear con `scale`.
export const PROP_NATURAL_SCALE = {
  // celestes / espacio
  sun: 2.5, moon: 2, star: 1.6, planet: 3, rocket: 4, cloud: 3, balloon: 2.5,
  // naturaleza
  tree: 3.5, palm: 3.2, cactus: 2.4, plant: 3, bush: 4, flower: 1.8, 'flower-cluster': 1.9,
  'tall-grass': 3, mushroom: 2, rock: 4, fountain: 2.5, pond: 3.5, coral: 2.2, seaweed: 2.3,
  // interior / mobiliario
  table: 2.4, chair: 1.8, bookshelf: 3, blackboard: 2.5, lamp: 2.7, candle: 2,
  rug: 4, 'rug-stripes': 4, 'rug-medallion': 3.5, 'rug-checker': 4, book: 1.6, computer: 2.5,
  // objetos
  crate: 3.5, barrel: 2, chest: 3, coin: 2, gem: 1.8, pokeball: 2, pedestal: 2.5, bell: 3, domino: 3, field: 1,
  cat: 3, vault: 3.5, pomegranate: 1.6, column: 4, wheat: 3, chasm: 4, wonderflower: 2.4, 'tree-bare': 3.5, basilisk: 6, aiorb: 3, notebook: 3, genially: 3,
  // comunes (tragedia de los comunes)
  pasture: 3, sheep: 3, fence: 3.5,
  // paradoja de Zenón
  turtle: 2.8,
  // urbano / estructuras
  building: 3.5, streetlamp: 3, lighthouse: 3.5, boat: 2.8, door: 3, sign: 2.4, bench: 2.6,
  // animados / interactivos
  butterfly: 2.5, bird: 2.5, fish: 2.5, rabbit: 2.5, bee: 2.5, frog: 2.5,
  swing: 5, clock: 3, bonfire: 3, switch: 3, 'path-tile': 4,
  // símbolos didácticos
  lightbulb: 2, hourglass: 2, scale: 2.2, magnifier: 2, key: 2, trophy: 2,
  flag: 2.2, flask: 2, globe: 2.2, scroll: 2, gear: 2, mountain: 4,
};
